;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg1 = #383d49
background = #0C0C10
fg = #e8e9e4


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00


;; colors
;black = #3B4252
red1 = #778F99
green1 = #7496C5
yellow1 = #95A0A5
blue1 = #C6C1B6
ocean = #6381C4
bluedark = #3D59A1
magenta1 = #9FC5D0
indigo1 = #6C77BB
indigolight1 = #808bcf
cyan1 = #B7C9CE
white = #ECEFF4
teal = #8FBCBB
;orange = 
;pink = 


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
