;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg1 = #383d49
background = #0f1016
fg = #b5b4c2


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00


;; colors
;black = #3B4252
red1 = #B25933
green1 = #9B675E
yellow1 = #DB9757
blue1 = #DBAB6C
ocean = #6381C4
bluedark = #3D59A1
magenta1 = #2F5996
indigo1 = #6C77BB
indigolight1 = #808bcf
cyan1 = #666890
white = #ECEFF4
teal = #8FBCBB
;orange = 
;pink = 


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
