;
;	 ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
;	██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
;	██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
;	██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
;	 ██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
; 	 ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝
;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

alpha = #0000ffff
bg1 = #383d49
background = #06121D
fg = #ec9daa


;; for 50% transparent
trans1 = #80000000 
;; 100% transparent
trans2 = #00


;; colors
;black = #3B4252
red1 = #BF616A
green1 = #A3BE8C
yellow1 = #EBCB8B
blue1 = #61afef
ocean = #6381C4
bluedark = #3D59A1
purple1 = #B48EAD
indigo1 = #6C77BB
indigolight1 = #808bcf
cyan = #88c0d0
white = #ECEFF4
teal = #8FBCBB
;orange = 
;pink = 


;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
