[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true
enable-click = true
enable-scroll = true

strip-wsnumbers = true
index-sort = false 

icon-0 = 1; 
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
icon-default = 

format = <label-state> 
# label-state-padding = 2

label-focused = %icon%

label-active-foreground = ${colors.background}
label-active-background = ${colors.primary}
label-occupied-foreground = ${colors.background-alt}
label-urgent-foreground = ${colors.alert}
label-empty-foreground = ${colors.foreground}

label-active-padding = 0
label-active-padding-right = 1

# label-empty-padding = 2
label-occupied-padding = 1

[module/pulseaudio]
type = custom/script
exec = ~/.config/i3/scripts/volumecontrol.sh --get
interval = 0.1
format = <label>
format-foreground = ${colors.foreground}
label = %output%
label-muted = 󰖁 
label-muted-foreground = #80ECFBF8
scroll-down = ~/.config/i3/scripts/volumecontrol.sh --dec
scroll-up = ~/.config/i3/scripts/volumecontrol.sh --inc
click-left = ~/.config/i3/scripts/volumecontrol.sh --toggle
click-right = pavucontrol


[module/tray]
type = internal/tray

format = <tray>
format-margin = 8px
tray-spacing = 8px


[network-base]
type = internal/network
interval = 5
; format-connected = <label-connected>
format-disconnected = <label-disconnected>

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = 󰌘  
label-connected-foreground = ${colors.foreground}


[module/date]
type = internal/date

interval = 1.0

time = " %I:%M %p "
time-alt = " %a, %d %b %Y "

format = <label>
format-padding = 1
label = %time%
label-foreground = ${colors.foreground}


# Power
[module/powermenu]
type = custom/text
content = " "
content-foreground = #B20000
click-left = ~/.config/i3/scripts/powermenu.sh


[module/cliphist]
type = custom/script
exec = ~/.config/i3/scripts/cliphist.sh --num
click-left = ~/.config/i3/scripts/cliphist.sh --hist
click-right = ~/.config/i3/scripts/cliphist.sh --clr
interval = 0.1
fotmat = <label>
label =  %output%
label-foreground = ${colors.foreground}

; User Modules
[module/updates]
type = custom/script
exec = ~/.config/i3/scripts/systemupdate.sh --check
tail = true
interval = 86400
format = <label>
format-prefix = 󰏔
format-prefix-foreground = ${colors.foreground}
format-padding = 0
label = " %output% "
label-foreground = ${colors.foreground}
click-left = ~/.config/i3/scripts/systemupdate.sh --update

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/launcher]
type = custom/text
content = " "
icon-size = 30

; "content" has the same properties as "format-NAME"
content-foreground = ${colors.foreground}
content-padding = 1

click-left = ~/.config/i3/scripts/menu_select.sh 2
# click-right = kitty --title ranger -e ranger

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/sepl]
type = custom/text
; content = ")› "
content = " "

content-background = ${colors.background}
content-foreground = ${colors.clr1}
content-padding = 0

[module/sepr]
type = custom/text
; content = " ‹("
content = ""

content-background = ${colors.background}
content-foreground = ${colors.clr1}
content-padding = 0


[module/wall]
type = custom/script
exec = echo ""
click-left = ~/.config/i3/scripts/Wallpaper.sh

