#---------------- colors & gap ----------------#

# class                 border  backgr. text    indicator child_border
client.focused          #0E1317 #2F4A5D #524D5F #960A1B  #DA061A
client.focused_inactive #524D5F #960A1B #0E1317 #FB000F  #960A1B
client.unfocused        #524D5F #0E1317 #a7b5c1 #960A1B  #960A1B
client.urgent           #DA061A #FB000F #0E1317 #0E1317  #FB000F
client.placeholder      #CD3255 #CD3255 #0E1317 #CD3255  #CD3255

client.background       #ffffff
